
  
version: "3.1"

services:
  postgres:
    image: postgres
    container_name: postgres-instagram-tools
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - 5432:5432